# Generated by Codex on 2026-03-21

from django.db import migrations, models
import uuid


def _set_booking_ids(apps, schema_editor):
    TakeAppointment = apps.get_model('appointment', 'TakeAppointment')
    for row in TakeAppointment.objects.all():
        if not row.booking_id:
            row.booking_id = uuid.uuid4().hex[:12].upper()
            row.save(update_fields=['booking_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='booking_id',
            field=models.CharField(default='', editable=False, max_length=12),
        ),
        migrations.RunPython(_set_booking_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='takeappointment',
            name='booking_id',
            field=models.CharField(default='', editable=False, max_length=12, unique=True),
        ),
    ]
