# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_add_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='applied', max_length=12),
        ),
    ]
