# Generated by Django 5.2.12 on 2026-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_department_free_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takeappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                ],
                default="applied",
                max_length=12,
            ),
        ),
    ]
