# Generated by Codex on 2026-03-22

from django.db import migrations, models
import appointment.models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_alter_takeappointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="takeappointment",
            name="appointment_date",
            field=models.DateField(default=appointment.models._default_appt_date),
        ),
        migrations.AddField(
            model_name="takeappointment",
            name="appointment_time",
            field=models.TimeField(default=appointment.models._default_appt_time),
        ),
    ]
