# Generated by Codex on 2026-03-22

from django.db import migrations, models
import appointment.models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_add_booking_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="takeappointment",
            name="appointment_duration_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="takeappointment",
            name="appointment_end_time",
            field=models.TimeField(default=appointment.models._default_appt_time),
        ),
    ]
