# Generated by Codex on 2026-03-22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0007_add_booking_duration_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="avg_minutes_per_patient",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="takeappointment",
            name="token_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="takeappointment",
            name="estimated_start_time",
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
