# Generated by Codex on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0008_token_queue_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="takeappointment",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
