# Generated by Codex on 2026-03-22

from django.db import migrations, models
import uuid


def _fill_appointment_uuid(apps, schema_editor):
    Appointment = apps.get_model("appointment", "Appointment")
    existing = set(
        Appointment.objects.exclude(uuid__isnull=True).values_list("uuid", flat=True)
    )
    for row in Appointment.objects.filter(uuid__isnull=True):
        new_id = uuid.uuid4()
        while new_id in existing:
            new_id = uuid.uuid4()
        row.uuid = new_id
        row.save(update_fields=["uuid"])
        existing.add(new_id)


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0009_add_email_takeappointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(_fill_appointment_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="appointment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
