# Generated by Codex on 2026-03-22

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def _fill_appointment_slug(apps, schema_editor):
    Appointment = apps.get_model("appointment", "Appointment")
    existing = set(
        Appointment.objects.exclude(slug__isnull=True).exclude(slug__exact="").values_list("slug", flat=True)
    )
    for row in Appointment.objects.filter(slug__isnull=True) | Appointment.objects.filter(slug__exact=""):
        base = slugify((row.full_name or "").strip()) or "doctor"
        slug = base
        if slug in existing:
            slug = f"{base}-{uuid.uuid4().hex[:8]}"
        while slug in existing:
            slug = f"{base}-{uuid.uuid4().hex[:8]}"
        row.slug = slug
        row.save(update_fields=["slug"])
        existing.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0010_add_appointment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="slug",
            field=models.SlugField(blank=True, max_length=130, null=True),
        ),
        migrations.RunPython(_fill_appointment_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="appointment",
            name="slug",
            field=models.SlugField(blank=True, max_length=130, unique=True),
        ),
    ]
