# Generated by Codex on 2026-03-22

from django.db import migrations, models
from datetime import datetime, time


def _parse_time_value(value, default_time):
    if isinstance(value, time):
        return value
    if value is None:
        return default_time
    value = str(value).strip()
    if not value:
        return default_time
    candidates = ["%I %p", "%I:%M %p", "%H:%M", "%H:%M:%S"]
    for fmt in candidates:
        try:
            return datetime.strptime(value, fmt).time()
        except ValueError:
            continue
    return default_time


def _backfill_time_fields(apps, schema_editor):
    Appointment = apps.get_model("appointment", "Appointment")
    for row in Appointment.objects.all():
        row.start_time_new = _parse_time_value(row.start_time, time(9, 0))
        row.end_time_new = _parse_time_value(row.end_time, time(17, 0))
        row.save(update_fields=["start_time_new", "end_time_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0011_add_appointment_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="start_time_new",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time_new",
            field=models.TimeField(null=True),
        ),
        migrations.RunPython(_backfill_time_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="appointment",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="end_time",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="start_time_new",
            new_name="start_time",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="end_time_new",
            new_name="end_time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(default=time(9, 0)),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(default=time(17, 0)),
        ),
    ]
